[2023-03-03T16:01:17.672+0100] {processor.py:154} INFO - Started process (PID=57143) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:01:17.678+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:01:17.678+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:01:17.678+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:01:17.732+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:01:17.732+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:01:17.732+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:01:17.732+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:01:17.732+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:01:17.862+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.191 seconds
[2023-03-03T16:03:18.148+0100] {processor.py:154} INFO - Started process (PID=57240) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:03:18.154+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:03:18.154+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:03:18.154+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:03:18.203+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:03:18.202+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:03:18.203+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:03:18.203+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:03:18.203+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:03:18.317+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2023-03-03T16:04:34.165+0100] {processor.py:154} INFO - Started process (PID=57299) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:04:34.170+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:04:34.171+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:04:34.170+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:04:34.218+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:04:34.218+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:04:34.219+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:04:34.219+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:04:34.219+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:04:34.327+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.163 seconds
[2023-03-03T16:05:47.850+0100] {processor.py:154} INFO - Started process (PID=57346) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:05:47.857+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:05:47.857+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:05:47.857+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:05:47.918+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:05:47.918+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:05:47.918+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:05:47.918+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:05:47.919+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:05:48.083+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.234 seconds
[2023-03-03T16:07:08.482+0100] {processor.py:154} INFO - Started process (PID=57398) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:07:08.488+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:07:08.488+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:07:08.488+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:07:08.550+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:07:08.549+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:07:08.550+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:07:08.550+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:07:08.550+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:07:08.662+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.181 seconds
[2023-03-03T16:08:29.177+0100] {processor.py:154} INFO - Started process (PID=57452) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:08:29.182+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:08:29.182+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:08:29.182+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:08:29.228+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:08:29.228+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:08:29.228+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:08:29.228+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:08:29.228+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:08:29.332+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.156 seconds
[2023-03-03T16:09:46.716+0100] {processor.py:154} INFO - Started process (PID=57502) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:09:46.723+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:09:46.723+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:09:46.723+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:09:46.777+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:09:46.777+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:09:46.778+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:09:46.778+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:09:46.778+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:09:46.908+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.193 seconds
[2023-03-03T16:11:02.852+0100] {processor.py:154} INFO - Started process (PID=57547) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:11:02.858+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:11:02.858+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:11:02.858+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:11:02.912+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:11:02.912+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:11:02.912+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:11:02.912+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:11:02.912+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:11:03.035+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2023-03-03T16:12:21.697+0100] {processor.py:154} INFO - Started process (PID=57586) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:12:21.703+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:12:21.703+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:12:21.703+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:12:21.754+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:12:21.754+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:12:21.754+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:12:21.754+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:12:21.755+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:12:21.863+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.167 seconds
[2023-03-03T16:13:33.929+0100] {processor.py:154} INFO - Started process (PID=57624) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:13:33.935+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:13:33.936+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:13:33.935+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:13:33.984+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:13:33.984+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:13:33.984+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:13:33.984+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:13:33.985+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:13:34.091+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.162 seconds
[2023-03-03T16:14:50.181+0100] {processor.py:154} INFO - Started process (PID=57690) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:14:50.186+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:14:50.187+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:14:50.187+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:14:50.234+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:14:50.233+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:14:50.234+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:14:50.234+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:14:50.234+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:14:50.353+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2023-03-03T16:16:07.641+0100] {processor.py:154} INFO - Started process (PID=57750) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:16:07.646+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:16:07.647+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:16:07.647+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:16:07.704+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:16:07.703+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:16:07.704+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:16:07.704+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:16:07.704+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:16:07.819+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.179 seconds
[2023-03-03T16:17:27.327+0100] {processor.py:154} INFO - Started process (PID=57841) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:17:27.333+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:17:27.333+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:17:27.333+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:17:27.386+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:17:27.386+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:17:27.386+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:17:27.386+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:17:27.386+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:17:27.521+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.194 seconds
[2023-03-03T16:18:46.576+0100] {processor.py:154} INFO - Started process (PID=57896) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:18:46.582+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:18:46.582+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:18:46.582+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:18:46.635+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:18:46.635+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:18:46.636+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:18:46.636+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:18:46.636+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:18:46.759+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2023-03-03T16:20:02.949+0100] {processor.py:154} INFO - Started process (PID=57952) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:20:02.954+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:20:02.955+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:20:02.955+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:20:03.004+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:20:03.003+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:20:03.004+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:20:03.004+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:20:03.004+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:20:03.111+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.163 seconds
[2023-03-03T16:21:23.442+0100] {processor.py:154} INFO - Started process (PID=58039) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:21:23.449+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:21:23.449+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:21:23.449+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:21:23.513+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:21:23.512+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:21:23.513+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:21:23.513+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:21:23.513+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:21:23.628+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2023-03-03T16:22:42.442+0100] {processor.py:154} INFO - Started process (PID=58091) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:22:42.447+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:22:42.447+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:22:42.447+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:22:42.497+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:22:42.496+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:22:42.497+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:22:42.497+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:22:42.497+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:22:42.599+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2023-03-03T16:23:57.551+0100] {processor.py:154} INFO - Started process (PID=58171) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:23:57.556+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:23:57.556+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:23:57.556+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:23:57.601+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:23:57.601+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:23:57.601+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:23:57.601+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:23:57.602+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:23:57.708+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2023-03-03T16:25:14.254+0100] {processor.py:154} INFO - Started process (PID=58219) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:25:14.259+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:25:14.259+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:25:14.259+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:25:14.307+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:25:14.307+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:25:14.307+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:25:14.307+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:25:14.307+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:25:14.427+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2023-03-03T16:26:28.746+0100] {processor.py:154} INFO - Started process (PID=58259) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:26:28.752+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:26:28.752+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:26:28.752+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:26:28.797+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:26:28.797+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:26:28.797+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:26:28.797+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:26:28.797+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:26:28.912+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.167 seconds
[2023-03-03T16:27:43.063+0100] {processor.py:154} INFO - Started process (PID=58308) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:27:43.067+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:27:43.068+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:27:43.068+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:27:43.116+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:27:43.116+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:27:43.116+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:27:43.116+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:27:43.116+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:27:43.227+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.165 seconds
[2023-03-03T16:28:58.893+0100] {processor.py:154} INFO - Started process (PID=58346) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:28:58.897+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:28:58.897+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:28:58.897+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:28:58.943+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:28:58.943+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:28:58.944+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:28:58.944+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:28:58.944+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:28:59.047+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2023-03-03T16:30:14.830+0100] {processor.py:154} INFO - Started process (PID=58392) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:30:14.837+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:30:14.837+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:30:14.837+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:30:14.888+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:30:14.887+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:30:14.888+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:30:14.888+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:30:14.888+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:30:14.995+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.165 seconds
[2023-03-03T16:31:30.896+0100] {processor.py:154} INFO - Started process (PID=58434) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:31:30.902+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:31:30.903+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:31:30.902+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:31:30.955+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:31:30.955+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:31:30.955+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:31:30.955+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:31:30.955+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:31:31.071+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.176 seconds
[2023-03-03T16:32:48.048+0100] {processor.py:154} INFO - Started process (PID=58472) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:32:48.054+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:32:48.054+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:32:48.054+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:32:48.102+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:32:48.102+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:32:48.103+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:32:48.102+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:32:48.103+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:32:48.208+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.161 seconds
[2023-03-03T16:34:05.554+0100] {processor.py:154} INFO - Started process (PID=58534) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:34:05.560+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:34:05.561+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:34:05.561+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:34:05.613+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:34:05.612+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:34:05.613+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:34:05.613+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:34:05.613+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:34:05.732+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.178 seconds
[2023-03-03T16:35:21.655+0100] {processor.py:154} INFO - Started process (PID=58578) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:35:21.661+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:35:21.661+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:35:21.661+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:35:21.713+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:35:21.713+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:35:21.713+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:35:21.713+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:35:21.713+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:35:21.823+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2023-03-03T16:36:38.332+0100] {processor.py:154} INFO - Started process (PID=58621) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:36:38.338+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:36:38.338+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:36:38.338+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:36:38.386+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:36:38.386+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:36:38.387+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:36:38.386+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:36:38.387+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:36:38.490+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2023-03-03T16:37:56.532+0100] {processor.py:154} INFO - Started process (PID=58664) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:37:56.538+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:37:56.539+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:37:56.538+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:37:56.597+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:37:56.597+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:37:56.597+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:37:56.597+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:37:56.598+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:37:56.724+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.193 seconds
[2023-03-03T16:39:13.766+0100] {processor.py:154} INFO - Started process (PID=58702) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:39:13.772+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:39:13.773+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:39:13.773+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:39:13.823+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:39:13.823+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:39:13.824+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:39:13.824+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:39:13.824+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:39:13.935+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2023-03-03T16:40:50.382+0100] {processor.py:154} INFO - Started process (PID=58758) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:40:50.387+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:40:50.388+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:40:50.388+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:40:50.438+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:40:50.438+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:40:50.438+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:40:50.438+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:40:50.438+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:40:50.547+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2023-03-03T16:42:20.671+0100] {processor.py:154} INFO - Started process (PID=58805) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:42:20.677+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:42:20.677+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:42:20.677+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:42:20.731+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:42:20.730+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:42:20.731+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:42:20.731+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:42:20.731+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:42:20.866+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2023-03-03T16:43:54.282+0100] {processor.py:154} INFO - Started process (PID=58882) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:43:54.288+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:43:54.289+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:43:54.289+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:43:54.341+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:43:54.341+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:43:54.341+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:43:54.341+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:43:54.342+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:43:54.448+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2023-03-03T16:45:29.948+0100] {processor.py:154} INFO - Started process (PID=58936) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:45:29.955+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:45:29.956+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:45:29.955+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:45:30.011+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:45:30.011+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:45:30.012+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:45:30.012+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:45:30.012+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:45:30.151+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.203 seconds
[2023-03-03T16:47:03.831+0100] {processor.py:154} INFO - Started process (PID=59008) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:47:03.837+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:47:03.838+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:47:03.837+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:47:03.891+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:47:03.891+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:47:03.891+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:47:03.891+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:47:03.891+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:47:04.011+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.180 seconds
[2023-03-03T16:48:34.039+0100] {processor.py:154} INFO - Started process (PID=59061) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:48:34.045+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:48:34.046+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:48:34.046+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:48:34.094+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:48:34.094+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:48:34.094+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:48:34.094+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:48:34.094+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:48:34.203+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.165 seconds
[2023-03-03T16:50:08.497+0100] {processor.py:154} INFO - Started process (PID=59118) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:50:08.502+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:50:08.503+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:50:08.502+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:50:08.553+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:50:08.552+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:50:08.553+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:50:08.553+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:50:08.553+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:50:08.667+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.172 seconds
[2023-03-03T16:51:41.959+0100] {processor.py:154} INFO - Started process (PID=59180) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:51:41.964+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:51:41.965+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:51:41.965+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:51:42.015+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:51:42.014+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:51:42.015+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:51:42.015+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:51:42.015+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:51:42.143+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.185 seconds
[2023-03-03T16:53:12.287+0100] {processor.py:154} INFO - Started process (PID=59228) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:53:12.292+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:53:12.293+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:53:12.293+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:53:12.341+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:53:12.340+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:53:12.341+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:53:12.341+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:53:12.341+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:53:12.443+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.157 seconds
[2023-03-03T16:54:40.260+0100] {processor.py:154} INFO - Started process (PID=59287) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:54:40.266+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:54:40.266+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:54:40.266+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:54:40.316+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:54:40.315+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:54:40.316+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:54:40.316+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:54:40.316+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:54:40.420+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
[2023-03-03T16:56:15.768+0100] {processor.py:154} INFO - Started process (PID=59337) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:56:15.773+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:56:15.773+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:56:15.773+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:56:15.828+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:56:15.828+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:56:15.828+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:56:15.828+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:56:15.829+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:56:15.947+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.180 seconds
[2023-03-03T16:57:47.828+0100] {processor.py:154} INFO - Started process (PID=59389) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:57:47.833+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:57:47.834+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:57:47.833+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:57:47.879+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:57:47.879+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:57:47.879+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:57:47.879+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:57:47.880+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:57:47.980+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2023-03-03T16:59:22.764+0100] {processor.py:154} INFO - Started process (PID=59434) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:59:22.770+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T16:59:22.771+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:59:22.771+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:59:22.825+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:59:22.824+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T16:59:22.825+0100] {logging_mixin.py:137} INFO - [2023-03-03T16:59:22.825+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T16:59:22.825+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T16:59:22.954+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.190 seconds
[2023-03-03T17:00:55.341+0100] {processor.py:154} INFO - Started process (PID=59481) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:00:55.348+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:00:55.348+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:00:55.348+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:00:55.399+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:00:55.399+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:00:55.400+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:00:55.399+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:00:55.400+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:00:55.522+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.181 seconds
[2023-03-03T17:02:28.675+0100] {processor.py:154} INFO - Started process (PID=59531) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:02:28.680+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:02:28.681+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:02:28.680+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:02:28.725+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:02:28.725+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:02:28.725+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:02:28.725+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:02:28.725+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:02:28.830+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.156 seconds
[2023-03-03T17:03:59.420+0100] {processor.py:154} INFO - Started process (PID=59596) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:03:59.425+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:03:59.426+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:03:59.426+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:03:59.478+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:03:59.477+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:03:59.478+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:03:59.478+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:03:59.478+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:03:59.589+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.170 seconds
[2023-03-03T17:05:28.630+0100] {processor.py:154} INFO - Started process (PID=59643) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:05:28.636+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:05:28.636+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:05:28.636+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:05:28.684+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:05:28.684+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:05:28.684+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:05:28.684+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:05:28.684+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:05:28.811+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.182 seconds
[2023-03-03T17:07:04.478+0100] {processor.py:154} INFO - Started process (PID=59699) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:07:04.483+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:07:04.483+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:07:04.483+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:07:04.545+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:07:04.545+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:07:04.546+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:07:04.545+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:07:04.546+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:07:04.648+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.171 seconds
[2023-03-03T17:08:46.074+0100] {processor.py:154} INFO - Started process (PID=59763) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:08:46.079+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:08:46.080+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:08:46.080+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:08:46.126+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:08:46.125+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:08:46.126+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:08:46.126+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:08:46.126+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:08:46.235+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.162 seconds
[2023-03-03T17:10:14.878+0100] {processor.py:154} INFO - Started process (PID=59811) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:10:14.883+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:10:14.883+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:10:14.883+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:10:14.929+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:10:14.928+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:10:14.929+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:10:14.929+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:10:14.929+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:10:15.031+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.154 seconds
[2023-03-03T17:11:42.038+0100] {processor.py:154} INFO - Started process (PID=59862) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:11:42.042+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:11:42.042+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:11:42.042+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:11:42.085+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:11:42.085+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:11:42.085+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:11:42.085+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:11:42.085+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:11:42.186+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.149 seconds
[2023-03-03T17:13:13.127+0100] {processor.py:154} INFO - Started process (PID=59943) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:13:13.131+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:13:13.131+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:13:13.131+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:13:13.177+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:13:13.177+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:13:13.178+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:13:13.178+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:13:13.178+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:13:13.279+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2023-03-03T17:14:45.155+0100] {processor.py:154} INFO - Started process (PID=60009) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:14:45.163+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:14:45.163+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:14:45.163+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:14:45.222+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:14:45.222+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:14:45.222+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:14:45.222+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:14:45.222+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:14:45.387+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.233 seconds
[2023-03-03T17:16:17.763+0100] {processor.py:154} INFO - Started process (PID=60064) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:16:17.769+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:16:17.769+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:16:17.769+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:16:17.815+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:16:17.815+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:16:17.815+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:16:17.815+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:16:17.816+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:16:17.921+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2023-03-03T17:17:48.619+0100] {processor.py:154} INFO - Started process (PID=60120) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:17:48.625+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:17:48.626+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:17:48.626+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:17:48.680+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:17:48.679+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:17:48.680+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:17:48.680+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:17:48.680+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:17:48.807+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2023-03-03T17:19:18.119+0100] {processor.py:154} INFO - Started process (PID=60179) to work on /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:19:18.125+0100] {processor.py:756} INFO - Processing file /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-03-03T17:19:18.125+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:19:18.125+0100] {dagbag.py:537} INFO - Filling up the DagBag from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:19:18.172+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:19:18.172+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-03-03T17:19:18.172+0100] {logging_mixin.py:137} INFO - [2023-03-03T17:19:18.172+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-03-03T17:19:18.173+0100] {processor.py:768} WARNING - No viable dags retrieved from /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-03-03T17:19:18.274+0100] {processor.py:176} INFO - Processing /Users/uab910/dev/nnam-poc/pyenv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
